language: rust
sudo: false

jobs:
    include:
        - env: ARCH=x86_64
          rust: stable
          os: linux
        - env: ARCH=i686
          rust: stable
          os: linux
        - env: ARCH=x86_64
          rust: stable
          os: osx
        - env: ARCH=i686
          rust: stable
          os: osx
        - env: ARCH=x86_64
          rust: 1.32.0
          os: linux
        - env: ARCH=i686
          rust: 1.32.0
          os: linux
        - env: ARCH=x86_64
          rust: nightly
          os: linux
        - env: ARCH=i686
          rust: nightly
          os: linux
        - env: ARCH=x86_64
          rust: beta
          os: linux
        - env: ARCH=i686
          rust: beta
          os: linux

install:
    - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
    - export HOST=$ARCH-$OS
    - if [ $ARCH = 'i686' ]; then rustup target add $HOST; fi

script:
    - cargo test --no-default-features --target "$HOST"
    - cargo test --target "$HOST"
